
name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch the latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }} # or your PAT if you are using one
          max_post_count: "4"
          feed_list: "https://dev.to/feed/itszed0"
